### ISSUE TITLE
请问当前环境支持并发的Http请求吗？

### ISSUE THREAD

**Issue by konieshadow** [aliyun/fc-runtime-go-sdk#14]
在实际测试过程中，使用fc.StartHttp(handler)启动的服务，在并发接收请求时会出现请求体互相错乱的问题。即请求B的请求体变成了同时发出的请求A的请求体，导致程序异常。

**Comment by fanzhe328** [comment]
能否给一下复现的方法？

**Comment by fanzhe328** [comment]
fix in #15 
请使用 v0.2.0 版本
